server:
  port: 8081

spring:
  application:
    name: harness-admin
  datasource:
    url: jdbc:mysql://localhost:3306/harness_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 5Jlk0QDa64gPdfsP8drshaPWqogEb6eFTitEq+WKey/KjvQLmMFe8UNtHLTLpE8UEnDymu6FyAyilQBlnLX4hg==
  expiration: 86400000

admin:
  init:
    username: admin
    password: Admin@123456
    role: SUPER_ADMIN
